# 1. Pull Docker Registry image
- name: Pull Docker Registry image
  community.docker.docker_image:
    name: registry
    source: pull

# 2. Create directory for registry config.yml
- name: Create directory for registry config.yml
  file: 
    path: /etc/docker/registry	
    state: directory

# 3. Configure registry config.yml
- name: Configure registry config.yml
  copy: 
    dest: /etc/docker/registry/config.yml
    content: | 
      proxy:			
        remoteurl: https://registry-1.docker.io

# 4. Create docker registry container
- name: Create docker registry container
  community.docker.docker_container:
    name: registry	
    image: registry
    detach: true
    recreate: true
    restart_policy: unless-stopped
    mounts:
    - type: bind
      source: /etc/docker/registry/
      target: /etc/registry
    ports:
    - 5000:5000
    state: started

# 5. Update daemon.js
- name: Update daemon.json
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "registry-mirrors": ["http://localhost:5000"]
      }

# 6. Restart docker daemon
- name: Restart docker daemon
  systemd:
    name: docker
    state: restarted
